version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_PASSWORD: example
    networks:
      - wp-network
    volumes:
      - ./wordpress:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    networks:
      - wp-network
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  wp-network:
